# Generated by Django 3.1.4 on 2021-01-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=30)),
                ('OwnerId', models.IntegerField()),
                ('AppHeader', models.CharField(max_length=50)),
                ('AppContent', models.TextField(max_length=1000)),
                ('AppPhoto', models.ImageField(default='DefaultAppImage.png', upload_to='')),
                ('AppType', models.CharField(max_length=10)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
