# Generated by Django 3.1.4 on 2021-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=30)),
                ('OwnerId', models.IntegerField()),
                ('PostId', models.IntegerField()),
                ('PostType', models.CharField(max_length=10)),
                ('Comment', models.TextField(max_length=150)),
                ('CommentDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=30)),
                ('OwnerId', models.IntegerField()),
                ('ForumHeader', models.CharField(max_length=50)),
                ('ForumContent', models.TextField(max_length=1000)),
                ('ForumisActive', models.BooleanField(default=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=30)),
                ('OwnerId', models.IntegerField()),
                ('IdeaHeader', models.CharField(max_length=50)),
                ('IdeaContent', models.TextField(max_length=1000)),
                ('IdeaPhoto', models.ImageField(default='DefaultIdeaImage.png', upload_to='')),
                ('IdeaType', models.CharField(max_length=10)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=30)),
                ('OwnerId', models.IntegerField()),
                ('PostId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaveDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=30)),
                ('OwnerId', models.IntegerField()),
                ('PostId', models.IntegerField()),
                ('PostType', models.CharField(max_length=10)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
