# Generated by Django 3.1.4 on 2021-01-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_commentdatas_forum_idea_likedatas_savedatas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='AppPhoto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='IdeaPhoto',
            field=models.ImageField(upload_to=''),
        ),
    ]
