# Generated by Django 3.1.4 on 2021-01-05 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210104_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='AppLink',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
