# Generated by Django 3.1.4 on 2021-01-07 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='MailDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
