# Generated by Django 3.1.4 on 2021-01-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_mails_maildate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='AppPhoto',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
