# Generated by Django 3.1.4 on 2021-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='AppPhoto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
